plugins {
    id "com.gradleup.shadow" version "9.6.1"
    id "io.micronaut.application" version "5.0.2"
}

version = "0.4"
group = "de.gumerbaev"

repositories {
    mavenCentral()
}

dependencies {
    annotationProcessor "io.micronaut:micronaut-http-validation"
    implementation "io.micronaut:micronaut-http-client"
    implementation "io.micronaut:micronaut-jackson-databind"
    implementation "io.micronaut.validation:micronaut-validation"
    implementation "io.micronaut.cache:micronaut-cache-caffeine"
    implementation "io.micronaut.views:micronaut-views-thymeleaf"
    implementation "jakarta.annotation:jakarta.annotation-api"

    implementation 'org.fusesource.jansi:jansi:2.4.3'
    implementation "org.jsoup:jsoup:1.23.2"

    runtimeOnly "org.slf4j:slf4j-nop"
    runtimeOnly "org.yaml:snakeyaml"
}

application {
    mainClass.set("de.gumerbaev.Application")
}

java {
    sourceCompatibility = JavaVersion.toVersion("25")
    targetCompatibility = JavaVersion.toVersion("25")
}

graalvmNative.toolchainDetection = false
micronaut {
    runtime("jetty")
    testRuntime("junit5")
    processing {
        incremental(true)
        annotations("de.gumerbaev.*")
    }
}
