micronaut:
  server:
    host: 0.0.0.0
  application:
    name: wikibook
  router:
    static-resources:
      images:
        enabled: true
        paths: classpath:public/images
        mapping: /images/**
  caches:
    boxes:
      expire-after-write: 1h
