micronaut:
  server:
    host: 0.0.0.0
  application:
    name: wikibook
  router:
    static-resources:
      images:
        mapping: /images/*
        paths: classpath:images
  caches:
    boxes:
      expire-after-write: 3h
